'use strict';

// Based on eslint:recommended, with adjustments to make behaviour similar to old CB JSLint setup
// Explanation of rules: https://eslint.org/docs/rules/
module.exports = {
    parserOptions: {
        "ecmaVersion": 2017
    },
    env: {
        "es6": true,
        'browser': true
    },
    rules: {
        'accessor-pairs': 'off',
        'array-bracket-newline': 'off',
        'array-bracket-spacing': ['error', 'never'],
        'array-callback-return': 'off',
        'array-element-newline': 'off',
        'arrow-body-style': 'off',
        'arrow-parens': 'off',
        'arrow-spacing': 'off',
        'block-scoped-var': 'off',
        'block-spacing': ['error', 'never'],
        'brace-style': 'error',
        'callback-return': 'off',
        camelcase: 'error',
        'capitalized-comments': 'off',
        'class-methods-use-this': 'off',
        'comma-dangle': ['error', 'only-multiline'],
        'comma-spacing': ['error', { 'before': false, 'after': true }],
        'comma-style': ['error', 'last'],
        complexity: 'off',
        'computed-property-spacing': ['error', 'never'],
        'consistent-return': 'off',
        'consistent-this': 'off',
        'constructor-super': 'error',
        curly: 'error',
        'default-case': 'off',
        'dot-location': ['error', 'property'],
        'dot-notation': ['error', { 'allowKeywords': false }],
        'eol-last': 'off',
        eqeqeq: 'error',
        'for-direction': 'off',
        'func-call-spacing': ['error', 'never'],
        'func-name-matching': 'off',
        'func-names': 'off',
        'func-style': ['error', 'expression', { 'allowArrowFunctions': true }],
        'function-paren-newline': ['error', 'never'],
        'generator-star-spacing': 'off',
        'getter-return': 'off',
        'global-require': 'off',
        'guard-for-in': 'error',
        'handle-callback-err': 'off',
        'id-blacklist': 'off',
        'id-length': 'off',
        'id-match': 'off',
        'implicit-arrow-linebreak': 'off',
        indent: 'error',
        'indent-legacy': 'off',
        'init-declarations': 'off',
        'jsx-quotes': 'off',
        'key-spacing': 'error',
        'keyword-spacing': ['error', { 'before': true, 'after': true }],
        'line-comment-position': 'error',
        'linebreak-style': 'off',
        'lines-around-comment': 'off',
        'lines-around-directive': 'off',
        'lines-between-class-members': 'error',
        'max-depth': 'off',
        'max-len': 'off',
        'max-lines': ['warn', {'max': 500, 'skipBlankLines': true, 'skipComments': true }],
        'max-nested-callbacks': ['error', { 'max': 5 }],
        'max-params': ['error', { 'max': 5 }],
        'max-statements': 'off',
        'max-statements-per-line': 'error',
        'multiline-comment-style': 'error',
        'multiline-ternary': 'off',
        'new-cap': 'error',
        'new-parens': 'off',
        'newline-after-var': 'error',
        'newline-before-return': 'off',
        'newline-per-chained-call': 'off',
        'no-alert': 'warn',
        'no-array-constructor': 'error',
        'no-await-in-loop': 'off',
        'no-bitwise': 'error',
        'no-buffer-constructor': 'off',
        'no-caller': 'off',
        'no-case-declarations': 'error',
        'no-catch-shadow': 'off',
        'no-class-assign': 'error',
        'no-compare-neg-zero': 'error',
        'no-cond-assign': 'error',
        'no-confusing-arrow': 'off',
        'no-console': 'off',
        'no-const-assign': 'error',
        'no-constant-condition': 'error',
        'no-continue': 'error',
        'no-control-regex': 'error',
        'no-debugger': 'error',
        'no-delete-var': 'error',
        'no-div-regex': 'off',
        'no-dupe-args': 'error',
        'no-dupe-class-members': 'error',
        'no-dupe-keys': 'error',
        'no-duplicate-case': 'error',
        'no-duplicate-imports': 'off',
        'no-else-return': 'error',
        'no-empty': 'error',
        'no-empty-character-class': 'error',
        'no-empty-function': 'error',
        'no-empty-pattern': 'error',
        'no-eq-null': 'off',
        'no-eval': 'error',
        'no-ex-assign': 'error',
        'no-extend-native': 'off',
        'no-extra-bind': 'off',
        'no-extra-boolean-cast': 'error',
        'no-extra-label': 'off',
        'no-extra-parens': 'off',
        'no-extra-semi': 'error',
        'no-fallthrough': 'error',
        'no-floating-decimal': 'off',
        'no-func-assign': 'error',
        'no-global-assign': 'error',
        'no-implicit-coercion': 'off',
        'no-implicit-globals': 'off',
        'no-implied-eval': 'off',
        'no-inline-comments': 'off',
        'no-inner-declarations': 'error',
        'no-invalid-regexp': 'error',
        'no-invalid-this': 'off',
        'no-irregular-whitespace': 'error',
        'no-iterator': 'off',
        'no-label-var': 'off',
        'no-labels': 'off',
        'no-lone-blocks': 'off',
        'no-lonely-if': 'error',
        'no-loop-func': 'off',
        'no-magic-numbers': 'off',
        'no-mixed-operators': 'error',
        'no-mixed-requires': 'off',
        'no-mixed-spaces-and-tabs': 'error',
        'no-multi-assign': 'error',
        'no-multi-spaces': 'off',
        'no-multi-str': 'off',
        'no-multiple-empty-lines': ['error', { 'max': 2, 'maxEOF': 1, 'maxBOF': 1 }],
        'no-native-reassign': 'off',
        'no-negated-condition': 'warn',
        'no-negated-in-lhs': 'off',
        'no-nested-ternary': 'off',
        'no-new': 'off',
        'no-new-func': 'off',
        'no-new-object': 'error',
        'no-new-require': 'off',
        'no-new-symbol': 'error',
        'no-new-wrappers': 'off',
        'no-obj-calls': 'error',
        'no-octal': 'error',
        'no-octal-escape': 'off',
        'no-param-reassign': 'off',
        'no-path-concat': 'off',
        'no-plusplus': ['error', { 'allowForLoopAfterthoughts': true }],
        'no-process-env': 'off',
        'no-process-exit': 'off',
        'no-proto': 'off',
        'no-prototype-builtins': 'off',
        'no-redeclare': 'error',
        'no-regex-spaces': 'error',
        'no-restricted-globals': 'off',
        'no-restricted-imports': 'off',
        'no-restricted-modules': 'off',
        'no-restricted-properties': 'off',
        'no-restricted-syntax': 'off',
        'no-return-assign': 'off',
        'no-return-await': 'off',
        'no-script-url': 'off',
        'no-self-assign': 'warn',
        'no-self-compare': 'off',
        'no-sequences': 'off',
        'no-shadow': 'off',
        'no-shadow-restricted-names': 'off',
        'no-spaced-func': 'off',
        'no-sparse-arrays': 'error',
        'no-sync': 'off',
        'no-tabs': 'error',
        'no-template-curly-in-string': 'off',
        'no-ternary': 'off',
        'no-this-before-super': 'error',
        'no-throw-literal': 'off',
        'no-trailing-spaces': ['error', {'ignoreComments': true}],
        'no-undef': 'error',
        'no-undef-init': 'off',
        'no-undefined': 'off',
        'no-underscore-dangle': 'error',
        'no-unexpected-multiline': 'error',
        'no-unmodified-loop-condition': 'off',
        'no-unneeded-ternary': 'error',
        'no-unreachable': 'error',
        'no-unsafe-finally': 'error',
        'no-unsafe-negation': 'error',
        'no-unused-expressions': 'off',
        'no-unused-labels': 'error',
        'no-unused-vars': 'error',
        'no-use-before-define': 'off',
        'no-useless-call': 'off',
        'no-useless-computed-key': 'off',
        'no-useless-concat': 'off',
        'no-useless-constructor': 'off',
        'no-useless-escape': 'error',
        'no-useless-rename': 'off',
        'no-useless-return': 'off',
        'no-var': 'error',
        'no-void': 'off',
        'no-warning-comments': 'off',
        'no-whitespace-before-property': 'error',
        'no-with': 'off',
        'nonblock-statement-body-position': 'off',
        'object-curly-newline': ['error', { 'multiline': true, 'minProperties': 1 }],
        'object-curly-spacing': 'error',
        'object-property-newline': ['error'],
        'object-shorthand': 'off',
        // Deliberate change from JSLint - see http://benalman.com/news/2012/05/multiple-var-statements-javascript/
        'one-var': ['error', { 'initialized': 'never', 'uninitialized': 'always' }],
        'one-var-declaration-per-line': 'error',
        'operator-assignment': 'off',
        'operator-linebreak': 'off',
        'padded-blocks': 'off',
        'padding-line-between-statements': 'off',
        'prefer-arrow-callback': 'off',
        'prefer-const': 'off',
        'prefer-destructuring': 'off',
        'prefer-numeric-literals': 'off',
        'prefer-promise-reject-errors': 'off',
        'prefer-reflect': 'off',
        'prefer-rest-params': 'off',
        'prefer-spread': 'off',
        'prefer-template': 'off',
        'quote-props': 'off',
        quotes: ['error', 'single', { 'avoidEscape': true }],
        radix: 'off',
        'require-await': 'off',
        'require-jsdoc': 'off',
        'require-yield': 'error',
        'rest-spread-spacing': 'off',
        semi: ['error', 'always'],
        'semi-spacing': 'error',
        'semi-style': ['error', 'last'],
        'sort-imports': 'off',
        'sort-keys': 'off',
        'sort-vars': 'off',
        'space-before-blocks': ['error', 'always'],
        'space-before-function-paren': ['error', {'anonymous': 'always', 'named': 'never', 'asyncArrow': 'always'}],
        'space-in-parens': 'error',
        'space-infix-ops': 'error',
        'space-unary-ops': 'error',
        'spaced-comment': 'error',
        strict: 'error',
        'switch-colon-spacing': 'error',
        'symbol-description': 'off',
        'template-curly-spacing': 'off',
        'template-tag-spacing': 'error',
        'unicode-bom': 'off',
        'use-isnan': 'error',
        'valid-jsdoc': 'off',
        'valid-typeof': 'error',
        'vars-on-top': 'error',
        'wrap-iife': 'off',
        'wrap-regex': 'off',
        'yield-star-spacing': 'off',
        yoda: 'off'
    }
};
